// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Close():Promise<Error>;

export function GetFilePath():Promise<string>;

export function Open():Promise<Error>;

export function OverWrite(arg1:Array<number>):Promise<Error>;

export function Read():Promise<Array<number>>;

export function Startup(arg1:context.Context):void;

export function Store(arg1:Array<number>):Promise<Error>;
