// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['storage']['FileStorage']['Close']();
}

export function GetFilePath() {
  return window['go']['storage']['FileStorage']['GetFilePath']();
}

export function Open() {
  return window['go']['storage']['FileStorage']['Open']();
}

export function OverWrite(arg1) {
  return window['go']['storage']['FileStorage']['OverWrite'](arg1);
}

export function Read() {
  return window['go']['storage']['FileStorage']['Read']();
}

export function Startup(arg1) {
  return window['go']['storage']['FileStorage']['Startup'](arg1);
}

export function Store(arg1) {
  return window['go']['storage']['FileStorage']['Store'](arg1);
}
