// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateTask(arg1:models.CreateTask):void;

export function GetAllTasks():Promise<Array<models.Task>>;

export function Start(arg1:context.Context):void;

export function StartTimedTask(arg1:models.Task):Promise<Error>;

export function Stop():void;
