// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['taskmanager']['TaskManager']['CreateTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['taskmanager']['TaskManager']['GetAllTasks']();
}

export function Load() {
  return window['go']['taskmanager']['TaskManager']['Load']();
}
