// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateTask(arg1:models.CreateTask):void;

export function GetAllTasks():Promise<Array<models.Task>>;

export function Load():void;
