// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['taskmanager']['TaskManager']['CreateTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['taskmanager']['TaskManager']['GetAllTasks']();
}

export function Start(arg1) {
  return window['go']['taskmanager']['TaskManager']['Start'](arg1);
}

export function StartTimedTask(arg1) {
  return window['go']['taskmanager']['TaskManager']['StartTimedTask'](arg1);
}

export function Stop() {
  return window['go']['taskmanager']['TaskManager']['Stop']();
}
